// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using projekt.NET.Data;

#nullable disable

namespace projekt.NET.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260618105229_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("projekt.NET.Models.Ingrediens", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Enhet")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mängd")
                        .HasColumnType("TEXT");

                    b.Property<string>("Namn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ReceptId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ReceptId");

                    b.ToTable("Ingrediens");
                });

            modelBuilder.Entity("projekt.NET.Models.Kategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Namn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Kategori");
                });

            modelBuilder.Entity("projekt.NET.Models.Recept", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Beskrivning")
                        .HasColumnType("TEXT");

                    b.Property<string>("Instruktioner")
                        .HasColumnType("TEXT");

                    b.Property<int>("KategoriId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tillagningstid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KategoriId");

                    b.ToTable("Recept");
                });

            modelBuilder.Entity("projekt.NET.Models.Ingrediens", b =>
                {
                    b.HasOne("projekt.NET.Models.Recept", "Recept")
                        .WithMany("Ingredienser")
                        .HasForeignKey("ReceptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recept");
                });

            modelBuilder.Entity("projekt.NET.Models.Recept", b =>
                {
                    b.HasOne("projekt.NET.Models.Kategori", "Kategori")
                        .WithMany("Recept")
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("projekt.NET.Models.Kategori", b =>
                {
                    b.Navigation("Recept");
                });

            modelBuilder.Entity("projekt.NET.Models.Recept", b =>
                {
                    b.Navigation("Ingredienser");
                });
#pragma warning restore 612, 618
        }
    }
}
